sudo: false

addons:
  apt:
    packages:
    - zlib1g-dev
    - libglew-dev
    - libleveldb-dev
    - libxrandr-dev
    - libxi-dev
    - libxcursor-dev
    - libxinerama-dev

branches:
  only:
  - master

before_install:
  - nvm install 7
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack setup

script:
  - stack test

cache:
  directories:
  - $HOME/.stack
