packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: 54e69a5ad3ccac24906bf611b68170deab75a4e5
  extra-dep: True
- location:
    git: https://github.com/lamdu/Algorithm-W-Step-By-Step
    commit: 6c3b6532182b6d3f896974aab8de8f223828eaba
  extra-dep: True
- location:
    git: https://github.com/lamdu/graphics-drawingcombinators
    commit: adf091973d26e80fac49764f03865f3e38a18c23
  extra-dep: True
- location:
    git: https://github.com/lamdu/freetype2
    commit: 71941659a29fe353bf975aefeb1805417c8ab364
  extra-dep: True
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 5a16cfb95490b3dbb019ff27a28ba4b63218d056
  extra-dep: True
- location:
    git: https://github.com/lamdu/FreetypeGL
    commit: 286b75894e51b08b7c63f8845f045f66d27e9849
  extra-dep: True
- location:
    git: https://github.com/lamdu/language-ecmascript
    commit: 1c75cfd064faec8c564c205702227bb44822e296
  extra-dep: True
- location:
    git: https://github.com/lamdu/nodejs-exec
    commit: 614cfa868899f2dde5801e1b95d4bc43815e9851
  extra-dep: True
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- stb-image-0.2.1
- GLFW-b-1.4.8.1
- bindings-GLFW-3.1.2.2
- testing-feat-0.4.0.3
- tagshare-0.0

resolver: nightly-2017-08-10

allow-newer: true
