packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: caebaca0e6b66c079a307608ee6dfea4df660d2b
  extra-dep: True
- location:
    git: https://github.com/lamdu/Algorithm-W-Step-By-Step
    commit: eb03220fb5fb7552e120723e2b32bebbfbb1749d
  extra-dep: True
- location:
    git: https://github.com/lamdu/graphics-drawingcombinators
    commit: 82f70c03a632402eb32d9e3bbb3fdd9a32492bd5
  extra-dep: True
- location:
    git: https://github.com/lamdu/freetype2
    commit: 520351a6e1cf5b18edae45d0e4a20758211fa8da
  extra-dep: True
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 5a16cfb95490b3dbb019ff27a28ba4b63218d056
  extra-dep: True
- location:
    git: https://github.com/lamdu/FreetypeGL
    commit: 286b75894e51b08b7c63f8845f045f66d27e9849
  extra-dep: True
- location:
    git: https://github.com/lamdu/nodejs-exec
    commit: 3635e2f4270bd5325fbada17af95f46fcde641cf
  extra-dep: True
- location:
    git: https://github.com/lamdu/GLFW-b
    commit: 66135b821a15568eaa906a277644fbc2b54d6de3
  extra-dep: True
- location:
    git: https://github.com/lamdu/bindings-GLFW
    commit: 216405c67dcc7783296ef0232d2936ac32341361
  extra-dep: True
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- language-ecmascript-0.17.2.0
- stb-image-0.2.1
- wl-pprint-1.2.1

resolver: lts-12.0

allow-newer: true
