packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: a330201de499ba0edf586337f3ecd491d3e66a75
  extra-dep: True
- location:
    git: https://github.com/lamdu/Algorithm-W-Step-By-Step
    commit: dcc4dece6a19d43bc7d8465d4e69917cfb900b0b
  extra-dep: True
- location:
    git: https://github.com/lamdu/graphics-drawingcombinators
    commit: 82f70c03a632402eb32d9e3bbb3fdd9a32492bd5
  extra-dep: True
- location:
    git: https://github.com/lamdu/freetype2
    commit: 71941659a29fe353bf975aefeb1805417c8ab364
  extra-dep: True
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 5a16cfb95490b3dbb019ff27a28ba4b63218d056
  extra-dep: True
- location:
    git: https://github.com/lamdu/FreetypeGL
    commit: 286b75894e51b08b7c63f8845f045f66d27e9849
  extra-dep: True
- location:
    git: https://github.com/lamdu/nodejs-exec
    commit: 7c763e1acf9c28d35aae034fdab6ee592ac8031d
  extra-dep: True
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- language-ecmascript-0.17.2.0
- stb-image-0.2.1
- wl-pprint-1.2.1

resolver: lts-12.0

allow-newer: true
