packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: f54abe6f1f9b1eb7923e442fa11f3cf16ad5cfcb
- location:
    git: https://github.com/lamdu/Algorithm-W-Step-By-Step
    commit: 9f07f5f00ac4aaebbc150f14ad8baa423442f1d5
- location:
    git: https://github.com/lamdu/graphics-drawingcombinators
    commit: c88a8c2b6d952315dc371f63b37622e7ecb56014
- location:
    git: https://github.com/lamdu/freetype2
    commit: b6b3f82b9f8acb925d8f36ecc1520832ad256444
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 839c7e00a7f48b33f13b7ce7914e713e4e2261ad
- location:
    git: https://github.com/lamdu/FreetypeGL
    commit: 585671664f9afb1dd306b0439007a0d5e9fe995a
- location:
    git: https://github.com/lamdu/language-ecmascript
    commit: 2c71e37ad055163a9926ee53e5297146de9b435c
- location:
    git: https://github.com/lamdu/nodejs-exec
    commit: 67272aca34a3ffc8dd35631215efc41a2061afeb
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- stb-image-0.2.1
- uuid-aeson-0.1.0.0

extra-include-dirs:
- /usr/local/include
extra-lib-dirs:
- /usr/local/lib
resolver: lts-5.12
