packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: fd0adff0a85bfa7c1fdb04165869a0cb5698d852
  extra-dep: True
- location:
    git: https://github.com/lamdu/Algorithm-W-Step-By-Step
    commit: f7b413dcf46d1ab959e3b2f1c6cd536864bc5663
  extra-dep: True
- location:
    git: https://github.com/lamdu/graphics-drawingcombinators
    commit: 2d44457f0b8385af600289cb1feca4cc03a6e39e
  extra-dep: True
- location:
    git: https://github.com/lamdu/freetype2
    commit: 71941659a29fe353bf975aefeb1805417c8ab364
  extra-dep: True
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 5a16cfb95490b3dbb019ff27a28ba4b63218d056
  extra-dep: True
- location:
    git: https://github.com/lamdu/FreetypeGL
    commit: 286b75894e51b08b7c63f8845f045f66d27e9849
  extra-dep: True
- location:
    git: https://github.com/lamdu/nodejs-exec
    commit: 7c763e1acf9c28d35aae034fdab6ee592ac8031d
  extra-dep: True
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- language-ecmascript-0.17.2.0
- stb-image-0.2.1
- GLFW-b-3.2.1.0
- tagshare-0.0
- wl-pprint-1.2.1
- size-based-0.1.1.0
- testing-feat-1.0.1.0
- testing-type-modifiers-0.1.0.1
- dictionary-sharing-0.1.0.0

resolver: nightly-2018-05-17

allow-newer: true
