packages:
- '.'
- location:
    git: https://github.com/lamdu/syntax-tree
    commit: d9e62518b72d6584b75fde07352e4c80ca90599e
  extra-dep: True
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: 91160d922971b3ff8f6d1d41960a4bd1534db8ec
  extra-dep: True
- location:
    git: https://github.com/lamdu/Algorithm-W-Step-By-Step
    commit: 5f1e1b36ff48b2001c30c3b731d61bf45b106d0b
  extra-dep: True
- location:
    git: https://github.com/lamdu/graphics-drawingcombinators
    commit: 82f70c03a632402eb32d9e3bbb3fdd9a32492bd5
  extra-dep: True
- location:
    git: https://github.com/lamdu/freetype2
    commit: 046328d92312d65638440132c016a3081d9c32a4
  extra-dep: True
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: c720425fc6ec3b68adfb7b25221723bab9520a9c
  extra-dep: True
- location:
    git: https://github.com/lamdu/leveldb-haskell
    commit: 6f2f0b88fd7197e74cbff92bde94168adce3fb29
  extra-dep: True
- location:
    git: https://github.com/lamdu/FreetypeGL
    commit: d2312f89cdf1412d584d13cda235ef683fa9c832
  extra-dep: True
- location:
    git: https://github.com/lamdu/nodejs-exec
    commit: 6a8b5c7897b822f523414fe2c0e666ecb8d4ab4b
  extra-dep: True
- location:
    git: https://github.com/lamdu/GLFW-b
    commit: a5222ed7ff5cb670b707cadb06bfe900339672f7
  extra-dep: True
- location:
    git: https://github.com/lamdu/bindings-GLFW
    commit: 8407bd91daa13e4c7f4cf0b29c736b038bc5c9de
  extra-dep: True
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- language-ecmascript-0.17.2.0
- stb-image-0.2.1
- wl-pprint-1.2.1
- ekg-core-0.1.1.4
- timeit-2.0
- aeson-diff-1.1.0.5

resolver: nightly-2018-11-15

flags:
  Lamdu:
    ekg: false

allow-newer: true
