packages:
- '.'
- location:
    git: https://github.com/lamdu/syntax-tree
    commit: 25a288a1bb3a8a7fc4b4fa79c544de19a71f6344
  extra-dep: True
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: d8325e9af0cec9ede007aed062a63f70f029f068
  extra-dep: True
- location:
    git: https://github.com/lamdu/graphics-drawingcombinators
    commit: 82f70c03a632402eb32d9e3bbb3fdd9a32492bd5
  extra-dep: True
- location:
    git: https://github.com/lamdu/freetype2
    commit: 046328d92312d65638440132c016a3081d9c32a4
  extra-dep: True
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 3e409dd8c5232abc53fd10e8138658333b90456f
  extra-dep: True
- location:
    git: https://github.com/lamdu/leveldb-haskell
    commit: 6f2f0b88fd7197e74cbff92bde94168adce3fb29
  extra-dep: True
- location:
    git: https://github.com/lamdu/FreetypeGL
    commit: d2312f89cdf1412d584d13cda235ef683fa9c832
  extra-dep: True
- location:
    git: https://github.com/lamdu/nodejs-exec
    commit: 6a8b5c7897b822f523414fe2c0e666ecb8d4ab4b
  extra-dep: True
- location:
    git: https://github.com/lamdu/GLFW-b
    commit: a5222ed7ff5cb670b707cadb06bfe900339672f7
  extra-dep: True
- location:
    git: https://github.com/lamdu/bindings-GLFW
    commit: 8407bd91daa13e4c7f4cf0b29c736b038bc5c9de
  extra-dep: True
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- stb-image-0.2.1

resolver: lts-13.15

flags:
  Lamdu:
    ekg: false

allow-newer: true
