packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: 560de341a268b51e51d745007adb3270eb9f5d5d
  extra-dep: True
- location:
    git: https://github.com/lamdu/Algorithm-W-Step-By-Step
    commit: f56f7482594e44a998060a279f4ec017241c6e10
  extra-dep: True
- location:
    git: https://github.com/lamdu/graphics-drawingcombinators
    commit: 83b468a530ff2c3b9ebd6b1fc018714d2a7b4907
  extra-dep: True
- location:
    git: https://github.com/lamdu/freetype2
    commit: 71941659a29fe353bf975aefeb1805417c8ab364
  extra-dep: True
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 5a16cfb95490b3dbb019ff27a28ba4b63218d056
  extra-dep: True
- location:
    git: https://github.com/lamdu/FreetypeGL
    commit: 286b75894e51b08b7c63f8845f045f66d27e9849
  extra-dep: True
- location:
    git: https://github.com/lamdu/nodejs-exec
    commit: 614cfa868899f2dde5801e1b95d4bc43815e9851
  extra-dep: True
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- language-ecmascript-0.17.2.0
- stb-image-0.2.1
- GLFW-b-1.4.8.1
- testing-feat-0.4.0.3
- tagshare-0.0

resolver: lts-10.5

allow-newer: true
