packages:
- '.'
- location:
    git: https://github.com/lamdu/syntax-tree
    commit: f30124163e1c65725bfbc95193cc793c5aff1179
  extra-dep: True
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: e57d99244f27d9b6d5d7b9ff0002c58bf4a89b0d
  extra-dep: True
- location:
    git: https://github.com/lamdu/graphics-drawingcombinators
    commit: 6253576fdd9233df5c3f43002310f38b0928c2d5
  extra-dep: True
- location:
    git: https://github.com/lamdu/freetype2
    commit: 046328d92312d65638440132c016a3081d9c32a4
  extra-dep: True
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: c178be550fbffe135435478a71fcb1dad537963a
  extra-dep: True
- location:
    git: https://github.com/lamdu/leveldb-haskell
    commit: 6f2f0b88fd7197e74cbff92bde94168adce3fb29
  extra-dep: True
- location:
    git: https://github.com/lamdu/FreetypeGL
    commit: d2312f89cdf1412d584d13cda235ef683fa9c832
  extra-dep: True
- location:
    git: https://github.com/lamdu/nodejs-exec
    commit: 6a8b5c7897b822f523414fe2c0e666ecb8d4ab4b
  extra-dep: True
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- stb-image-0.2.1
- unicode-properties-3.2.0.0

resolver: lts-13.15

flags:
  Lamdu:
    ekg: false

allow-newer: true
